<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DungeonChessBattle.Core\DungeonChessBattle.Core.csproj" />
    <ProjectReference Include="..\DungeonChessBattle.Client\DungeonChessBattle.Client.csproj" />
    <ProjectReference Include="..\DungeonChessBattle.GameConfig\DungeonChessBattle.GameConfig.csproj" />
    <ProjectReference Include="..\DungeonChessBattle.Server\DungeonChessBattle.Server.csproj" />
  </ItemGroup>
</Project>
