<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DungeonChessBattle.Protocol\DungeonChessBattle.Protocol.csproj" />
        <ProjectReference Include="..\DungeonChessBattle.Entities\DungeonChessBattle.Entities.csproj" />
        <ProjectReference Include="..\DungeonChessBattle.Server.Abstractions\DungeonChessBattle.Server.Abstractions.csproj" />
        <ProjectReference Include="..\DungeonChessBattle.Server.Lobby\DungeonChessBattle.Server.Lobby.csproj" />
        <ProjectReference Include="..\DungeonChessBattle.Server.Battle\DungeonChessBattle.Server.Battle.csproj" />
        <ProjectReference Include="..\DungeonChessBattle.Server.DataStore\DungeonChessBattle.Server.DataStore.csproj" />
        <ProjectReference Include="..\DungeonChessBattle.Server.DataStore.Shared\DungeonChessBattle.Server.DataStore.Shared.csproj" />
    </ItemGroup>

</Project>
